### ISSUE TITLE
3차원 CHL 처방을 위한 ESM4 코드 수정 (CHL-MJO 분석)

### ISSUE THREAD

**Issue by HyunChaeJung** [HCJung-jbnu/ESM4-PDAF#11]
- 50년 spin-up, on cobalt, manizza
- spin-up 이후 20년 run
  ~~- chl feedbakc on : on cobalt + manizza~~
  ~~- climatology 처방 : off cobalt + mainzza ( chl data 활용 시, 3차원 chl 사용하도록 코드 수정 필요)~~
    ~~- /parameterization/vertical/MOM_opacity.F90 에서 3차원 CHL DATA 들어가로독 코드 수정 -> chl output이 35층이라 연직 내삽 필요~~
  ~~- daily 확인 : chl, sst, mld, wind, olr~~

- 관련 옵션
  - ~/INPUT/MOM_input
```
 ! === module MOM_opacity ===
VAR_PEN_SW = True               !   [Boolean] default = False
                                ! If true, use one of the CHL_A schemes specified by
                                ! OPACITY_SCHEME to determine the e-folding depth of
                                ! incoming short wave radiation.
OPACITY_SCHEME = "MANIZZA_05"
```
    - ~/INPUT/MOM_override
    - input.nml

**Comment by HCJung-jbnu** [comment]
## spin-up period
- 13년 + 10년 + 10년 + 10년 + 7년 = 50년 완료
- 1999년 런중
- 2021년 런 필요

**Comment by HCJung-jbnu** [comment]
### 코드 수정
- namelist 족에 3dchl 옵션 넣어서 적용 
- 수정 코드 : MOM_opacity.F90
                     MOM_diabatic_driver.F90                      
                     /INPUT/MOM_input
                    ESM4/src/FMS/axis_utils/axis_utils.F90
                    ESM4/src/FMS/time_interp/time_interp_external.F90
                    ESM4/src/mom6/src/MOM6/src/tracer/MOM_offline_main.F90  
                    diag_table <-- Chl_3D : 처방된 3차원 chl outputs (mg/m3)
- 파일 chl 단위(kg/m3) * 1000000. = MOM6 optic chl 단위(mg/m3)

**Comment by HCJung-jbnu** [comment]
- diag_table 수정 : off cobalt + 3dchl 20년 런 완료
- diag_table 수정 : on colbat  20년 런 완료

**Comment by HCJung-jbnu** [comment]
- 모델 수행
- 57y_restart 사용, cobalt case : 1989~2010(22년 런)
  - cobalt : 1989, 1990 ~ 1996, 1997 ~ 2003, 2004 ~ 2009, 2010
  - daily chl 처방 : 1990 ~ 1999, 2000 ~ 2009
  - clim daily chl 처방 : 1990 ~ 1999, 2000 ~ 2009 
  - gas dataset_entry는 1990으로 고정
